stages:
  - deploy

deploy_production:
  stage: deploy
  image: node:4.2.2
  script:
    - ssh "$PRD_USER@$PRD_HOST" './killall-hub-process.sh || true'
    - ssh "$PRD_USER@$PRD_HOST" 'rm -rf ~/hub-befitter || true'
    - ssh "$PRD_USER@$PRD_HOST" 'mkdir -p ~/hub-befitter/ || true'
    - scp -r ./* "$PRD_USER@$PRD_HOST:~/hub-befitter/"
    - ssh "$PRD_USER@$PRD_HOST" "cd hub-befitter; yarn install; yarn build"
    - ssh "$PRD_USER@$PRD_HOST" "cd hub-befitter; yarn start -p 3001 > /dev/null 2>&1 &"
  tags:
    - release
  only:
    - main
  when: manual
