stages:
  - deploy

deploy_production:
  stage: deploy
  image: node:4.2.2
  script:
    # - yarn remove eslint && yarn add --dev eslint@"<8.0.0"
    - yarn install
    - yarn build
    - ssh "$PRD_HOST" './killall-website-process.sh || true'
    - ssh "$PRD_HOST" 'rm -rf ~/befitter-homepage || true'
    - ssh "$PRD_HOST" 'mkdir -p ~/befitter-homepage/.next || true'
    - scp -r .next/* "$PRD_HOST:~/befitter-homepage/.next"
    - ssh "$PRD_HOST" 'yarn start > /dev/null 2>&1 &'
  tags:
    - befitter-website
  only:
    - master
  when: manual